#server:
#  port: 8081

spring:
  application:
    name: fashionpedia-api-gateway

  cloud:
    gateway:
      default-filters:
        - RewritePath=/api/v1/(?<segment>.*), /$\{segment}
      routes:
        - id: report_service_route
          uri: http://report.fashionpedia.my.id
          predicates:
            - Path=
              /api/v1/report/**,
        - id: account_service_route
          uri: http://account.fashionpedia.my.id
          predicates:
            - Path=
              /api/v1/auth/**, 
        - id: buysell_service_route
          uri: http://buysell.fashionpedia.my.id
          predicates:
            - Path=
              /api/v1/seller/**, 
              /api/v1/buyer/**, 
              /api/v1/buysell/**
        - id: payment_service_route
          uri: http://payment.fashionpedia.my.id
          predicates:
            - Path=
              /api/v1/top-up/**, 
              /api/v1/pembayaran/**
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
